<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.confluent</groupId>
    <artifactId>jms-adapter</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>jms-adapter-examples</artifactId>
  <packaging>jar</packaging>
  <name>Kafka JMS Queue Adapter - Examples</name>
  <description>Example clients for the Kafka JMS Queue Adapter</description>

  <dependencies>
    <dependency>
      <groupId>io.confluent</groupId>
      <artifactId>kafka-jms-queue-adapter</artifactId>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>${exec-maven-plugin.version}</version>
        <configuration>
          <mainClass>${exec.mainClass}</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <properties>
    <exec.mainClass>io.confluent.jms.JmsQueueClient</exec.mainClass>
  </properties>

  <profiles>
    <profile>
      <id>client</id>
      <properties>
        <exec.mainClass>io.confluent.jms.JmsQueueClient</exec.mainClass>
      </properties>
    </profile>
    <profile>
      <id>simulate</id>
      <properties>
        <exec.mainClass>io.confluent.jms.JmsQueueSimulation</exec.mainClass>
      </properties>
    </profile>
    <profile>
      <id>listener</id>
      <properties>
        <exec.mainClass>io.confluent.jms.JmsQueueListener</exec.mainClass>
      </properties>
    </profile>
  </profiles>
</project>
